services:
  - type: web
    name: hostel-backend
    env: python
    region: oregon
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn hostel_erp.wsgi:application"
