services:
  - type: web
    name: hostel-backend
    env: python
    region: oregon
    branch: main
    buildCommand: |
        pip install -r requirements.txt
        python manage.py migrate
        python manage.py createsu
    startCommand: "gunicorn hostel_erp.wsgi:application"
